### ISSUE TITLE
Utilizar mappers para modificar a la persona jugadora

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#1]
Hay varios lugares donde se repite el patrón _Retornar jugador con x propiedades cambiadas_. Se podría abstraer esta lógica en mappers para hacer el código más declarativo.

Ejemplos: 
https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L38

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L41

**Comment by Tsoiffer** [comment]
se crean los mappers: editarTactica, editarDinero, sumarAcciones, editarNombre y sumarPropiedad
