### ISSUE TITLE
gritar - Lambda no necesaria

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#10]
Ojo con las lambdas! Si bien crea la función necesaria que tomaría al jugador y editaría el nombre, se puede resolver mejor con la aplicación parcial del `++`!

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/059029611ffe6f8f9b33d1397acd5e8e34588558/Haskell/src/tp_monopoly.hs#L44

**Comment by Tsoiffer** [comment]
Se utiliza aplicación parcial para evitar el uso de una función lambda
