### ISSUE TITLE
odiaA/2 - charles

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#12]
Charles odia a las personas de la mansión, no a cualquier persona.

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/27c39062dbf3ed7adf424bdfaf741163c816d360/Prolog/MuerteEnLaMansionDreadbuty.pl#L14

**Comment by Tsoiffer** [comment]
se corrige
