### ISSUE TITLE
Variables en plural

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#15]
No debería estar en plural la variable ya que cada consulta responde un individuo.

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/27c39062dbf3ed7adf424bdfaf741163c816d360/Prolog/MuerteEnLaMansionDreadbuty.pl#L13

**Comment by Tsoiffer** [comment]
se corrige
