### ISSUE TITLE
Función subastar - lógica de guardas

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#2]
Ojo con estas guardas. En los retornos donde matcheás las acciones, se retorna lo mismo (Lógica repetida). Si ambas acciones retornan lo mismo, podría ser mejor utilizar un "o" lógico para matchear ambas.

También, vería una manera de abstraer la lógica de restar el valor de la propiedad y añadirla en diferentes funciones, para que quede más declarativo y expresivo.
https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L46-L50

**Comment by Tsoiffer** [comment]
se edita la función subastar, se utilizo un "o" para machear y evitar la repetición de lógica.  Se creo la función auxiliar comprarPropiedad para abstraer la lógica
