### ISSUE TITLE
Subastar y hacerBerrinchePor - Repetición de Lógica

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#3]
Ojo que hay una repetición de lógica en estos retornos

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L48

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L67

**Comment by Tsoiffer** [comment]
se crean las funciones auxiliares verificacion y continuarConBerriches para evitar la repetición de lógica de las guardas de subastar y hacerBerrinchePor
