### ISSUE TITLE
cobrarAlquileres - Expresividad

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#4]
¡Buena abstracción barataOCara!

Sin embargo, hay algo que no me queda claro: ¿Por qué la multiplicación por 10 a lo que retorne esta función? Estaría más expresivo si esta nos retorna el valor del alquiler de la propiedad, y nos ahorra el calculo de esa multiplicación.

Algo más que agregaría es abstraer el map a una función auxiliar (Por ejemplo transformarAValoresDeAlquileres)

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L52-L58

**Comment by Tsoiffer** [comment]
se crea la función auxiliar dineroDeAlquileres para abstraer el sum y el map, se corrige barataOCara abstrayendo la multiplicación y retornando el valor a cobrar
