### ISSUE TITLE
Repetición de lógica - Comparación accionista

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#5]
Abstraería las funciones que comparan las acciones del jugador, así se evitan estas repeticiones de lógica
https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L49

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L62

**Comment by Tsoiffer** [comment]
se crea la función esAccionista para abstraer la comparación
