### ISSUE TITLE
Juego Final

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#6]
Ojo con los retornos de strings. Si bien está bueno para verlo en la consola, lo que era necesario es retornar al jugador.

Puede parecer rara esta corrección, pero está bueno dividir lo que es la parte lógica con la parte de presentación. Por ejemplo, si se pidiera modificar las acciones del jugador ganador de la ronda, ¿Lo podría hacer con esta función?

Lo que sí se podría realizar es una función que retorne un String mostrando quién es el jugador ganador, para mostrarlo en pantalla, y esta función es la que se utiliza de manera de "presentación" en consola (no es pedida en el TP pero a modo de ejemplo)

Otra cosa a notar es que hay repetición de lógica en los retornos. Con el cambio a un retorno lógico, esto puede resolverse.

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/8724420794d2d7983357a171160323454a944e1f/Haskell/src/tp_monopoly.hs#L73-L77

**Comment by Tsoiffer** [comment]
se corrige la función juego final para que retorne el jugador ganador en caso de empate gana el jugador 2
