### ISSUE TITLE
editarDinero - Diferencia

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#7]
¡Muy buenas funciones auxiliares para modificar al jugador!

Algo a notar acá: ¿Es necesario pasar la diferencia de dinero?

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/b5173d6a3c835a1e500659b1585a08ab00da1a93/Haskell/src/tp_monopoly.hs#L99-L100

Por ejemplo, que pasa si acá en vez de pasar la función `(+)` la utilizás parcialmente con la diferencia: `(+50)`? (Ahora no va a tipar, pero si le sacamos la diferencia en la función auxiliar,  ¿Qué pasa?)
https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/b5173d6a3c835a1e500659b1585a08ab00da1a93/Haskell/src/tp_monopoly.hs#L37-L38

**Comment by Tsoiffer** [comment]
Se edita el mapper de editarDinero para que sea mas genérico editarDinero :: (Float -> Float) -> Persona -> Persona
