### ISSUE TITLE
Mappers

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#8]
Si bien están correctos en el ejercicio, ojo que estos pueden que no sirvan para algún próximo requerimiento.

Por ejemplo, ¿Qué pasa si me piden que debería sacarle todas las propiedades a un jugador? ¿Podría hacerlo con estos mappers?

Sumo estas preguntas para analizar la posibilidad de abstraer más estos mappers. La idea es que queden lo más abstractos posibles para poder utilizarlos en cualquier situación necesaria!

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/b5173d6a3c835a1e500659b1585a08ab00da1a93/Haskell/src/tp_monopoly.hs#L95-L109

**Comment by Tsoiffer** [comment]
se editan los mappers para hacerlos mas genéricos del tipo=  
editarElementoDelData :: (ElementoDelData -> ElementoDelData) -> Persona -> Persona
