### ISSUE TITLE
pagarAAccionistas - Lambda

### ISSUE THREAD

**Issue by Maxi-F** [Tsoiffer/ParadigmasDeProgramacion#9]
Se puede utilizar capaz la función `substract` aplicandola parcialmente para no utilizar una lambda!

https://github.com/Tsoiffer/ParadigmasDeProgramacion/blob/4182a3a90f046bf3b7c655fbe272c7eda11ab5e0/Haskell/src/tp_monopoly.hs#L52-L55

**Comment by Tsoiffer** [comment]
Se remplaza la función lambda por la función subtract
